import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Header from './widgets/header/header'
import Footer from './widgets/footer/footer'
import Container from './components/container/container'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html
			lang='en'
			className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
		>
			<body>
				<Container>
					<Header></Header>
          </Container>
					{children}
          <Container>
					<Footer></Footer>
				</Container>
			</body>
		</html>
	)
}
