import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import Header from './widgets/header/header'
import Footer from './widgets/footer/footer'
import Container from './components/container/container'
import Providers from './provider/providers'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata = {
	title: 'IT Run Academy',
	description: 'Generated by cre	ate next app',
}

export default function RootLayout({ children }) {
	return (
		<html
			lang='en'
			className={`${geistSans.variable} ${geistMono.variable} h-full antialiased   dark`}
		>
			<body>
				<Providers>
					<Container>
						<Header></Header>
						{children}
						<Footer></Footer>
					</Container>
				</Providers>
			</body>
		</html>
	)
}
